In [1]:
#Write a function to compute 5/0 and use try/except to catch the exceptions.

def divide():
    return 5/0

try:
    divide()
except ZeroDivisionError as ze:
    print("division by zero!")
except:
    print("Caught an exception")

division by zero!


In [5]:
#  Implement a Python program to generate all sentences where subject is in ["Americans",
#"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

sentence = [(sub+" "+ vb + " " + ob) for sub in subjects for vb in verbs for ob in objects]
for i in sentence:
    print (i)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [5]:
#Write a function so that the columns of the output matrix are powers of the input vector.

import numpy as np

def gen_vandermonde_matrix(ip,n,increasing=False):
    
    if not increasing:
        mat_op=np.array([x**(n-1-i) for x in ip for i in range(n)]).reshape(ip.size,n)
    elif increasing:
        mat_op=np.array([x**i for x in ip for i in range(n)]).reshape(ip.size,n)
    
    return mat_op

input=np.array([9,2,3,4,5])
no_col=4
mat_op_dec=gen_vandermonde_matrix(input,no_col,False)
mat_op_inc=gen_vandermonde_matrix(input,no_col,True)

print("Input matrix is ",input,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",mat_op_dec,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",mat_op_inc,"\n")


Input matrix is  [9 2 3 4 5] 

Vander matrix of the input array in decreasing order of powers:

 [[729  81   9   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   9  81 729]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 

